apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: infected-match
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infected-match
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: infected-store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infected-store
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: trace-fetch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trace-fetch
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: trace-store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trace-store
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi
